### PR TITLE
Batched preprocessing for 1M cell notebook... 

### PR DESCRIPTION
**Pull request by rilango**
To avoid failure to process more then 1 Million cells, most of the processing before filtering HVG is now batched. Dask is used for this purpose. Additional functions are added to utils to support this.

Apart from this a new verb is added to launch script to make development easier.

### CODE REVIEW

**Comment by avantikalal** [comment]
In cell 13, I don't see why conversion to anndata is necessary, since the HVG calculation is now being done outside anndata.

**Comment by rilango** [comment]
> In cell 13, I don't see why conversion to anndata is necessary, since the HVG calculation is now being done outside anndata.

Yes. I did not analyze cell 14 closely. We can remove cell 13 and migrate cell 14 to use cupy instead. I will send a patch soon.

**Comment by rilango** [comment]
> In cell 13, I don't see why conversion to anndata is necessary, since the HVG calculation is now being done outside anndata.

Resolved.

**Comment by avantikalal** [comment]
Looks good, I think we need some explanation of the changes inside the notebook. Could you add  a few lines above cell 2 explaining the use of dask here?

**Comment by rilango** [comment]
> Looks good, I think we need some explanation of the changes inside the notebook. Could you add a few lines above cell 2 explaining the use of dask here?

Done. Please check the documentation under 'Load and Prepare Data'

**Pull request merged**
